name: Main
on: push

jobs:
  ci:
    container: node:18.13.0
    runs-on: ubuntu-latest
    services:
      postgres:
        env:
          POSTGRES_PASSWORD: postgres
        image: postgres:15.1-alpine
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - uses: ariga/atlas-action@v0
        with:
          dir: pkgs/api/src/db/
          dir-format: atlas # Or: golang-migrate, liquibase, flyway, goose, dbmate
          dev-url: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"

      - name: Run Test
        run: cd pkgs/api/ && npm run test
        env:
          DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
