name: Main
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    container: node:18.13.0
    runs-on: ubuntu-latest
    services:
      postgres:
        env:
          POSTGRES_PASSWORD: postgres
        image: postgres:15.1-alpine
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Install Atlas
        run: |
          curl -sSf https://atlasgo.sh | sh
      - run: |
          cd ./pkgs/api/src/db && atlas schema apply --auto-approve --env local_main -u 'postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable'


      - name: Run Test
        run: cd pkgs/api/ && npm run test
        env:
          DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
